name: Link Checker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --no-progress --exclude-mail './**/*.html' './**/*.md' './**/*.css'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
